export enum DealDisplayPostion {
  DASHBOARD_DEAL_TOP_LIST = 'DASHBOARD_DEAL_TOP_LIST',

  DASHBOARD_DEAL_MIDDLE_LIST = 'DASHBOARD_DEAL_MIDDLE_LIST',

  DASHBOARD_DEAL_BOTTOM_LIST = 'DASHBOARD_DEAL_BOTTOM_LIST',

  DASHBOARD_DEAL_SIDE_LIST = 'DASHBOARD_DEAL_SIDE_LIST',
}
