export enum DealType {
  USA_FREEDEAL = 'USA_FREEDEAL',

  USA_PAIDDEAL = 'USA_PAIDDEAL',

  USA_BLACKFRIDAY = 'USA_BLACKFRIDAY',

  USA_CHRISTMAS = 'USA_CHRISTMAS',

  INDIA_FREEDEAL = 'INDIA_FREEDEAL',

  INDIA_PAIDDEAL = 'INDIA_PAIDDEAL',

  INDIA_DASARA = 'INDIA_DASARA',

  INDIA_DIWALI = 'INDIA_DIWALI',

  INDIA_BONALU = 'INDIA_BONALU',

  INDIA_AKSHYA = 'INDIA_AKSHYA',

  INDIA_SANKRANTHI = 'INDIA_SANKRANTHI',
}
